### ISSUE TITLE
Add new blog post to virtocommerce.com/blog

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#101]
### 5 Benefits of B2B Ecommerce Business Strategy

![image](https://user-images.githubusercontent.com/43222967/48914660-ffaa6c80-ee30-11e8-81fe-7185001af004.png)

**Comment by blazemachine** [comment]
Good day, Megan.
I need to know what do you expect to see after click on ref (in first chapter).
May you give me url for this? Also, I need a publish date for this news. And I need a main picture.
Thanks.

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/blog/5-benefits-of-b2b-ecommerce-business-strategy
