### ISSUE TITLE
Add a New Blog Post on Virto Commerce News: Ntara Press Release: www.virtocommerce.com/blog

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#103]
**Ntara Selects Virto Commerce Platform with Strategic Partnership Announcement**
Specializing in scalable ecommerce software solutions for manufacturers and distributors

Los Angeles, CA, November 15, 2018 (Newswire) - Ntara, an enterprise digital services agency, and Virto Commerce, a leading provider of B2B e-commerce software, today announced a strategic partnership to better serve manufacturers and distributors who are looking to expand their e-commerce capabilities and scalability within their digital ecosystem.

Ntara is a Certified Virto Commerce partner that provides e-commerce expertise and data-driven solutions to clients who want to transform their business and digital ecosystem. Ntara selected Virto Commerce over any other e-commerce software because of its superior architecture, which is flexible, scalable, opensource, and built on the Microsoft technology stack.

“We have added Virto Commerce as a key technology in our e-commerce line-up because it is among the most extensible and customizable platform on the market today,” said Andy Didyk, Vice President of Sales and Marketing at Ntara. “For clients that demand the ultimate level of flexibility, we often recommend Virto Commerce.”

Ntara’s partnership with Virto Commerce enables clients to optimize their customer experience, deploy multiple touchpoints, and share operational and technical capability across the entire organization. By implementing an e-commerce solution, clients will build stronger customer relationships and rapidly increase global online sales.

“Together the partnership between Ntara and Virto Commerce positions us as a top choice for manufacturers and distributors,” said Alexander Siniouguine, CEO and Founder of Virto Commerce. “With Ntara’s depth of experience and industry knowledge and our innovative Virto Commerce platform, we are uniquely positioned to achieve rapid e-commerce success for our clients.”

**About Ntara**

Ntara is a digital agency dedicated to harnessing the combined power of strategy, design, and technology to solve the challenges of marketing, sales, and IT organizations. Our solutions increase revenue, lower costs, and boost productivity. Ntara specializes in three specific, mid-market to enterprise verticals: branded manufacturers & distributors, healthcare & institutions, and technology companies. Visit https://ntara.com.

**About Virto Commerce**

Virto Commerce is a worldwide leader in B2B e-commerce software and was founded in 2011 by industry experts with decades of e-commerce experience. Virto Commerce provides our robust e-commerce technology, services, and expertise to over 100 companies worldwide.

Leveraging our open source e-commerce platform and hosted solution, our clients strategically use Virto Commerce to build stronger customer relationships and rapidly increase global online sales. For a demo, visit https://virtocommerce.com or reach out to info@virtocommerce.com.
![ntara_mark_blue](https://user-images.githubusercontent.com/43222967/49019336-8cf80480-f142-11e8-9b72-38315433fed9.jpg)

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/blog/ntara-selects-virto-commerce-platform-with-strategic-partnership-announcement
