### ISSUE TITLE
Switch Magento glossary page layout to the new template

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#113]
This layout is old - https://virtocommerce.com/glossary/magento-alternatives. 
This one is new - https://virtocommerce.com/glossary/best-ecommerce-platforms or https://virtocommerce.com/glossary/b2b-ecommerce-companies-websites. 
Please, switch from the old to new layout without changing the content. Need to remove left menu, add case study block - https://screencast.com/t/Kut4TQn7, put video down and change styles. 
Banners should be also replaced with the new ones.

**Comment by blazemachine** [comment]
Done.
![image](https://user-images.githubusercontent.com/43133766/49651569-65ae0b00-fa51-11e8-81b8-68fdc976f959.png)

**Comment by AndrewYunisov** [comment]
We need to add case studies block.

**Comment by tatarincev** [comment]
done https://virtocommerce.com/glossary/magento-alternatives
