### ISSUE TITLE
New glossary page for Thing Commerce

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#115]
Like we have dome with https://virtocommerce.com/glossary/conversational-commerce. Same layout. Text below.
[How is ‘Thing Commerce’ Transforming The Way We Do Business.docx](https://github.com/VirtoCommerce/vc-content/files/2650461/How.is.Thing.Commerce.Transforming.The.Way.We.Do.Business.docx)

**Comment by blazemachine** [comment]
Done.
![image](https://user-images.githubusercontent.com/43133766/49594566-f1fbf780-f997-11e8-9b09-3e5daa8bb10f.png)

**Comment by AndrewYunisov** [comment]
Looks OK for me. 
1) Please, add the attached graphic.  I think it could be shortened in size. 
2) 
![shutterstock_519384478](https://user-images.githubusercontent.com/27814609/49597498-9d537f00-f98d-11e8-8976-ee722feca9f6.jpg)
Please, release and add to the left menu here - https://virtocommerce.com/glossary.

**Comment by blazemachine** [comment]
Full page with picture:
![image](https://user-images.githubusercontent.com/43133766/49633647-f8cc4e00-fa1b-11e8-8f5a-2c331de21dc1.png)

**Comment by AndrewYunisov** [comment]
I would make it 2 times smaller. Can you give me the URL to check?

**Comment by blazemachine** [comment]
I can't. It is not released yet.

**Comment by tatarincev** [comment]
@AndrewYunisov  please check this issue on https://virtocommerce.com
