### ISSUE TITLE
As an anonymous user I want to signup into VC portal.

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#12]
As an anonymous user I want to signup into VC portal.

- [x] GIVEN I'm anonymous user 
WHEN I click Signup action 
THEN I should be redirected to SignUp form with Email text field, "Sign up for a free account" button, Login via GitHub button

- [x] GIVEN SignUp form
WHEN I enter valid email and press "Sign up for a free account" button
THEN I should be redirected Congratulation page with Congratulation message and Didn't get your account action.
THEN The "activate your account" email should be send to specified email address.

- [ ] GIVEN SignUp form
WHEN I enter invalid email and press "Sign up for a free account" button
THEN The warning message should be displayed

- [x] GIVEN Congratulation informer (page) 
WHEN I click Didn't get your account action
THEN I should be redirected to the "Didn't get your activation email" page

- [x] GIVEN "Didn't get your activation email" page
WHEN I enter an valid email address and press "Resend Activation Email" page 
THEN I should be redirected Congratulation page with Congratulation message and Didn't get your account action.

- [x] GIVEN SignUp form
WHEN I  Login-in VIA GitHub
THEN I should be redirected to GitHub

- [ ] GIVEN Activation email in my emailbox
WHEN I click activate your account link
THEN I should be redirected to Activate Account page with First Name, Last Name, Password, Confirm Password test fields, I have read and agree to the Terms of Use link and Onward button

- [x] GIVEN Activate your account page
WHEN I enter valid information into  First Name, Last Name, Password, Confirm Password test fields
WHEN I click Onward button
THEN My Account should be activated and I will be able to visit pricate pages

**Comment by n2pro** [comment]
I'm anonymous user  I see:
![1](https://user-images.githubusercontent.com/13115017/37415284-c2ceb81e-27b3-11e8-953c-dc6451ad4c7c.JPG)
I'm anonymous user I click get free account, I see :
![2](https://user-images.githubusercontent.com/13115017/37415350-ea7fd5fa-27b3-11e8-9175-022800cfdfa4.JPG)
I enter invalid email, I see:
![3](https://user-images.githubusercontent.com/13115017/37415448-1aa502a0-27b4-11e8-9a34-ca2b258a5e5c.JPG)
Didn't get your activation email, I see
![4](https://user-images.githubusercontent.com/13115017/37415455-1ed9a272-27b4-11e8-93c2-2b69c9902afe.JPG)
Activate your account page:
![5](https://user-images.githubusercontent.com/13115017/37415457-211a8f56-27b4-11e8-8d03-8db26effe550.JPG)
