### ISSUE TITLE
Updates for https://virtocommerce.com/case-studies/kupinatao

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#120]
1. New case study file attached. 
[Virto Commerce Case Study Alibaba Kupinatao 2018.pdf](https://github.com/VirtoCommerce/vc-content/files/2660852/Virto.Commerce.Case.Study.Alibaba.Kupinatao.2018.pdf)
2. Building a National E-Commerce Leader -> Adapting a National Ecommerce Marketplace
3. New quote: 
“Using Virto Commerce platform capabilities, we created powerful marketplace system. We addressed order management, inventory, pricing, as well as developed a system of gathering, publishing, and managing customer reviews. This system helps Kupinatao customers make the right choice out of millions of positions and drives our sales.” 
4. Challenge section can be taken from CS text. 
5. От page https://virtocommerce.com/case-studies: 
5.1. Check why Play video is not working 
5.2. Created platform that allows sellers from china sell to the eastern europe countries. -> Created platform that allows sellers from China to sell to the Eastern Europe countries.

**Comment by blazemachine** [comment]
Done.
Case-studies page
![image](https://user-images.githubusercontent.com/43133766/49741714-dacf4980-fcb8-11e8-82f6-c61f7ae341a4.png)
Kupinatao page
![image](https://user-images.githubusercontent.com/43133766/49741813-06eaca80-fcb9-11e8-9c66-06c3e7dbe3f4.png)

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/case-studies/kupinatao
