### ISSUE TITLE
Update PDF and content for Case Study for Kupinatao on www.virtocommerce.com/case-studies

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#121]
Hello: Would you please update this case study for Kupinatao on the main case study page and on its individual page? 
1) Add on the main case studies page. 
Kupinatao Logo: 
![logo_kupinatao_main_page](https://user-images.githubusercontent.com/43222967/49704417-a334a480-fbc7-11e8-8868-504193a3f940.png)
Title: Adapting a National Ecommerce Marketplace

2) Then add a new click-though page to include:
Title: Adapting a National Ecommerce Marketplace

Overview: 
![image](https://user-images.githubusercontent.com/43222967/49704479-7df46600-fbc8-11e8-8e66-7ef0a079227a.png)

Attached is the PDF file for download.
[Virto Commerce Case Study Alibaba Kupinatao 2018.pdf](https://github.com/VirtoCommerce/vc-content/files/2661134/Virto.Commerce.Case.Study.Alibaba.Kupinatao.2018.pdf)

**Comment by blazemachine** [comment]
With changes from #120, it will look like that
![image](https://user-images.githubusercontent.com/43133766/50004456-01e38f00-ffc9-11e8-9e1b-1f686c408fee.png)

**Comment by blazemachine** [comment]
Good day. You need approve it or smth.

**Comment by mpennie** [comment]
Good day: Would you remove the bottom half of the text -- so that only this portion in the screenshot is displayed? They the user will be able to get the full case study when they download it. Thank you.
<img width="720" alt="screen shot 2018-12-19 at 9 41 02 am" src="https://user-images.githubusercontent.com/43222967/50237687-6197bc80-0372-11e9-93aa-15b50b6376d1.png">

**Comment by blazemachine** [comment]
Done.

**Comment by tatarincev** [comment]
https://virtocommerce.com/case-studies/kupinatao
