### ISSUE TITLE
Replace the Wrong image on Bosch Case Study Page - it is from Proffsmagasinet

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#126]
Please change the image to a Bosch case study image per the attached. (The one that is there is from Proffs even though it shows Bosch products).
![bosch-partner-portal-03 2](https://user-images.githubusercontent.com/43222967/49950451-b3d96900-feac-11e8-9353-1e699ecf5ae9.png)

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/49984838-632c4380-ff72-11e8-8a5a-9a868c8fc86d.png)
https://virtocommerce.com/case-studies/bosch
