### ISSUE TITLE
Lessons - Lesson 1 - How to run VirtoCommerce application locally

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#13]
As a Developer, I want to setup of VirtoCommerce application (Runtime version) locally, so that I could test solution with demo data locally.

Definition of done:
- [x] Prerequisites
- [x] Initial configuration of VirtoCommerce Platform (Runtime version)
- [x] Initial configuration of VirtoCommerce Modules (Runtime version)
- [x] Initial configuration of VirtoCommerce Demo Data 
- [x] Initial setup of VirtoCommerce Storefront (Runtime version)
- [x] Initial configuration of VirtoCommerce Storefront Theme
- [x] Basic orderflow process

**Comment by MalikJuly** [comment]
vc-content cloned

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-content/blob/lesson1/Pages/docs/lessons/lesson1.md

**Comment by OlegoO** [comment]
@n2pro Merge to DEV and QA

**Comment by OlegoO** [comment]
Ready for QA

**Comment by dimitri-ak** [comment]
After deploy to production I can see the following:
![image](https://user-images.githubusercontent.com/7642075/38313577-aa923f56-3824-11e8-907a-5af195488142.png)

Is it correct?

**Comment by OlegoO** [comment]
Published https://virtocommerce.com/docs/lessons/lesson1
