### ISSUE TITLE
Digital Experience Platforms page

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#139]
New glossary page. URL /digital-experience-platforms
[DXP - All About Digital Experience Platforms.docx](https://github.com/VirtoCommerce/vc-content/files/2715381/DXP.-.All.About.Digital.Experience.Platforms.docx)
Comments block needed, pic attached. Alt - Digital Experience Platforms. 
![shutterstock_493152733](https://user-images.githubusercontent.com/27814609/50523707-a9d97c00-0ae2-11e9-89b2-079d88f51527.jpg)

**Comment by blazemachine** [comment]
Done.
https://staging.virtocommerce.com/glossary/digital-experience-platforms

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/glossary/digital-experience-platforms
