### ISSUE TITLE
[Draft] Documentation - Platform Overview - Architecture Overview

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#14]
Modern Stack of technologies:
* .NET Framework
* .NET Core
* Angular - for SPA user interface. One of the major decisions for picking it is due to its popularity and quality documentation. 
* ASP.NET MVC - as a web hosting technology
* ASP.NET Web API - to implement REST services
* ASP.NET Identity - tasks related to authorization and authentication
* Entity Framework - ORM
* ElasticSearch  – full text search engine for catalog, customers and etc
* Azure Cloud
	
Modularity:
* Two independent layers for Storefront and Admin sites 
* Module as isolated unity with own repository, devopsm releases 

Microservices:
* Every VirtoCommerce module is ready to use Rest Microservice (UI and API)
* Swagger
* Azure API management

Scalability:
* Scale UP
* Scale Out

Extensibility:
* By installing module
* By using extension points inside module
* By creating a new version of module

**Comment by tatarincev** [comment]
This issue has been closed because it has no longer relevant to the current operation nature of issues.
You may reopen this issue if it has been closed in error.
