### ISSUE TITLE
Update platform-settings.md

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-content#148]
Need to update [platform-settings.md](https://github.com/VirtoCommerce/vc-content/blob/deploy/pages/docs/vc2devguide/deployment/platform-settings.md) as there is no other source to know the configuration options. The page was last updated in 2016, and many important settings are missing: EnableBundlesOptimizations, AutoInstallModuleBundles, Authentication, etc.

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/docs/vc2devguide/deployment/platform-settings
