### ISSUE TITLE
New Blog Post - Virto Commerce Product Release Notes February 2019 -- https://virtocommerce.com/blog/category/technical

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#150]
![image](https://user-images.githubusercontent.com/43222967/51752419-50765580-206c-11e9-8294-e3ef02b7440d.png)
[Virto Product Release Notes Jan 2019.pdf](https://github.com/VirtoCommerce/vc-content/files/2796554/Virto.Product.Release.Notes.Jan.2019.pdf)
![release notes](https://user-images.githubusercontent.com/43222967/51752445-5f5d0800-206c-11e9-847a-d5511716a81b.png)

**Comment by mpennie** [comment]
Hello Evgeny, would you please create a new blog post? Use the image as the blog artwork. Use the content pasted here as the blog post body. And can you also attached the PDF as well? If not, please ignore the PDF. Thank you.

![image](https://user-images.githubusercontent.com/43222967/51752537-959a8780-206c-11e9-8f73-73bd03ec1f08.png)

**Comment by tatarincev** [comment]
@blazemachine  Please take this issue to work

**Comment by blazemachine** [comment]
Learn more - link for pdf file.

**Comment by mpennie** [comment]
Yes – this looks good. Thank you.
Megan

**Comment by mpennie** [comment]
Hi @tatarincev -- Nick had more input. So -- We have an edit to the page -- can you please use this updated PDF? Also are you able to create a webpage of content and also have the PDF link?
[Virto Product Release Notes Jan 2019.pdf](https://github.com/VirtoCommerce/vc-content/files/2818420/Virto.Product.Release.Notes.Jan.2019.pdf)

**Comment by blazemachine** [comment]
Done.
![image](https://user-images.githubusercontent.com/43133766/52128162-0980f500-2656-11e9-889e-9f4cda045df8.png)

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/blog/virtocommerce-product-release-notes-february-2019
