### ISSUE TITLE
Improve the list structure on a Roadmap page

### ISSUE THREAD

**Issue by 5309** [VirtoCommerce/vc-content#159]
Page: https://virtocommerce.com/roadmap
Section "Updated in January 2019" has two columns with roadmap items.

New roadmap was released.
We have now: the first column contains 4 items (starting with "Migration to .NET Core Framework" and finishing with "Drastic Performance Improvements"), the second column contains 8 items (starting with "CMS Landing Page Builder" and finishing with "Property Management Improvements").

What should be done:
Please shift items "Full Context Searching in a Storefront" and "Property Management Improvements" (both header and description) to the first (left) column.

Expected result: the page will look more symmetric, there will be 6 items in each column.

**Comment by Woland2k** [comment]
@5309  you can actually move it around yourself https://github.com/VirtoCommerce/vc-content/blob/deploy/pages/roadmap.md

**Comment by blazemachine** [comment]
Done.
![image](https://user-images.githubusercontent.com/43133766/52346204-e59c2580-2a40-11e9-8194-9ff79b3a86bf.png)
Also you may see it on https://staging.virtocommerce.com/roadmap

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/roadmap
