### ISSUE TITLE
As a Contributor, I want to see Contributor section

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#16]
GIVEN I'm registered user
AND I don't sign the CLA for VirtoCommerce/vc-platform
THEN I should see that invitation to sign CLA and become contributor in vc-community section

GIVEN I'm registered user
AND I don't sign the CLA for VirtoCommerce/vc-platform
WHEN when I click to "Become a contributor"
THEN I should be redirected to https://cla-assistant.io/VirtoCommerce/vc-platform

GIVEN I'm registered user
WHEN I signed the CLA for VirtoCommerce/vc-platform
THEN I should see that I'm Contributor in vc-community section

**Comment by OlegoO** [comment]
Need investigate, how we can check that user has signed  the CLA for VirtoCommerce/vc-platform, because

https://github.com/cla-assistant/cla-assistant#faq
You can see the list of signees on the user interface. There is also a possibility for you to export the list as a .csv file.

**Comment by n2pro** [comment]
It is necessary to check the presence of the list. [cla-assistant issue](https://github.com/cla-assistant/cla-assistant/issues/166)

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
