### ISSUE TITLE
Post New Page in Virtocommerce.com NEWS for this Rainbow Sandals Press Release by Feb 11

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#162]
![image](https://user-images.githubusercontent.com/43222967/52512774-962e3480-2bbb-11e9-8e0c-d96f0bbd484d.png)

**Comment by mpennie** [comment]
Add this image
![rainbow virto](https://user-images.githubusercontent.com/43222967/52585030-90696680-2de8-11e9-92ec-491f4a2c654d.png)

**Comment by mpennie** [comment]
Is that image the right size? If not, please let me know what the dimensions are, and I will change it.

**Comment by blazemachine** [comment]
Done.
![image](https://user-images.githubusercontent.com/43133766/52590088-42914480-2e62-11e9-98ae-a0b9e0889eab.png)
Also, you may watch it on link:
https://staging.virtocommerce.com/blog/rainbow-sandals-selects-virto-commerce-platform-for-digital-commerce

**Comment by mpennie** [comment]
Hi - The image I sent is too large. Would you please remove it from the body of the post. And Please replace the cover with this attached image instead -- and center it -- or resize it? Thank you.
![rainbowpr cover](https://user-images.githubusercontent.com/43222967/52590491-44bdb980-2df6-11e9-83a4-6c5f83366974.png)

**Comment by blazemachine** [comment]
Please check the page on the same link. Picture was changed and removed from blog's content.

**Comment by mpennie** [comment]
Looks fantastic. Done – please close the issue. Thank you!

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/blog/rainbow-sandals-selects-virto-commerce-platform-for-digital-commerce
