### ISSUE TITLE
Remove G+ links from footer

### ISSUE THREAD

**Issue by Tanyaper** [VirtoCommerce/vc-content#168]
Hi,
We need to remove the G+ (google plus) link from the footer (social networks) as Google is shutting down Google Plus.

**Comment by tatarincev** [comment]
@blazemachine Could you take this?

**Comment by blazemachine** [comment]
Done. You may watch it on https://staging.virtocommerce.com

**Comment by Tanyaper** [comment]
Looks good, thanks!

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/
