### ISSUE TITLE
Fix Issues with Mobile Page - https://virtocommerce.com/docs/vc2devguide/deployment/storefront-deployment/deploy-from-github-to-microsoft-azure

### ISSUE THREAD

**Issue by Tanyaper** [VirtoCommerce/vc-content#183]
The following page, https://virtocommerce.com/docs/vc2devguide/deployment/storefront-deployment/deploy-from-github-to-microsoft-azure has some mobile usability issues that show up in google search console that need to be looked into.  These changes are not urgent.  Issues are (for the mobile page): 
1) text too small to read
2) clickable elements too close together
3) content wider than the screen

Thanks!

**Comment by blazemachine** [comment]
Done. You may watch it on https://staging.virtocommerce.com/docs/vc2devguide/deployment/storefront-deployment/deploy-from-github-to-microsoft-azure
