### ISSUE TITLE
 Lessons - Lesson 2 - How to import my catalog

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#19]
As a Developer, I want to import my products into catalog, so that I could test solution with my data locally.

Definition of done:
- [ ] Prerequisites Catalog file with 15 products
- [ ] Describe how to create Catalog Data in Excel format: SKU, Title, Properties, Price, Image(s). Supported types.
- [ ] Import and additional steps (like re-index, reset cache)
- [ ] Open a new product on Admin
- [ ] Open a new product on Storefront

**Comment by n2pro** [comment]
The second lesson can be seen on [qc](https://vc-public-qc.azurewebsites.net/docs/lessons/lesson2).
