### ISSUE TITLE
New Blog Post - Infographic

### ISSUE THREAD

**Issue by Tanyaper** [VirtoCommerce/vc-content#192]
We would like to add a new page to the blog: the text is attached and accompanying graphic is also attached.  The user should be able to click on the graphic to enlarge it.
The text should be above the graphic, and the page title should be "Top 5 Essential B2B Ecommerce Functions Infographic".   Thanks and please let me know if you have any questions. 

[Blog Post- B2B features.docx](https://github.com/VirtoCommerce/vc-content/files/3040404/Blog.Post-.B2B.features.docx)
![B2B ecommerce functions (1)](https://user-images.githubusercontent.com/46223450/55507203-24a3bd00-5625-11e9-9414-c3496392c275.png)

**Comment by tatarincev** [comment]
@blazemachine  could you take it in work?

**Comment by blazemachine** [comment]
@Tanyaper you may watch it on the https://staging.virtocommerce.com/blog
With image on the page is possible this variant, it looks may be huge or not. Is really need to add a possibility for scale?

**Comment by Tanyaper** [comment]
Hi,
It does look big, can we make it a bit smaller and add a black border around the image? Otherwise looks good,  Thanks!!

________________________________

**Comment by blazemachine** [comment]
@Tanyaper 
Please, check https://staging.virtocommerce.com/blog/infographic
Image size was changed. You may click on this image and watch in other mode.

**Comment by Tanyaper** [comment]
Looks great! Thanks!!

________________________________

**Comment by Tanyaper** [comment]
Hi, Ca we please put into production? Thanks!

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/blog/infographic
