### ISSUE TITLE
New blog post - Press Release - B2B Online Chicago

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#195]
Hi - Please create a new blog post under Virto News for this Press Release, and use the attached banner image. Thank you.
![image](https://user-images.githubusercontent.com/43222967/55837406-27475c00-5ad6-11e9-92bf-8c79cbb50554.png)

![Virto blog banner B2B Online Image](https://user-images.githubusercontent.com/43222967/55837331-e9e2ce80-5ad5-11e9-9740-6f144f0cc1a1.png)

**Comment by tatarincev** [comment]
@blazemachine  please take this task

**Comment by blazemachine** [comment]
@mpennie You may check the result on the https://staging.virtocommerce.com/blog/press-release-b2b-online-chicago page.

**Comment by mpennie** [comment]
Sergey, thank you. Would you change the headline to be “Virto Commerce at B2B Online Event in Chicago” (delete Press Release).
Thank you.
@Sergey Podguzov<mailto:spo@virtoway.com>

**Comment by blazemachine** [comment]
Done. Url has been changed. Check the https://staging.virtocommerce.com/blog/virto-commerce-at-b2b-online-event-in-chicago page.

**Comment by mpennie** [comment]
Great. Please publish live tomorrow, April 11 @Sergey Podguzov<mailto:spo@virtoway.com> thank you.

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/blog/virto-commerce-at-b2b-online-event-in-chicago
