### ISSUE TITLE
Fix Mobile & Table view on b2b-ecommerce-platform page

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#20]
We should fix Mobile & Table view on b2b-ecommerce-platform page 
on b2b-ecommerce-platform.

Acceptance Criteria:
- [x] Chrome (Mobile, Table, Desktop)
- [x] Safari (Mobile, Table, Desktop)
- [x] Edge (Mobile, Table, Desktop)
- [x] IE (Mobile, Table, Desktop)

**Comment by n2pro** [comment]
@OlegoO This page avalble [here](https://vc-public-qc.azurewebsites.net/b2b-ecommerce-platform) for verification.

**Comment by OlegoO** [comment]
Approved
