### ISSUE TITLE
New blog post: News section -- Press Release announcing RB2 Partnership

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#201]
Please post on: Tuesday May 7, 2019. Use this image as the header graphic. Thank you.

![Blog post PR for RB2 and Virto](https://user-images.githubusercontent.com/43222967/57175322-5748fd00-6dff-11e9-8ef1-c3a2b33dddb5.png)

![image](https://user-images.githubusercontent.com/43222967/57175295-e9043a80-6dfe-11e9-8a6c-381c716f4c6d.png)

**Comment by tatarincev** [comment]
@blazemachine Please take this in work

**Comment by blazemachine** [comment]
@mpennie You may watch the result on the https://staging.virtocommerce.com/blog page.

**Comment by mpennie** [comment]
Terrific. Thank you! Will you make it live on May 7th, 2019 please. Thank you.

**Comment by tatarincev** [comment]
done
