### ISSUE TITLE
Add New Case Study for Standaard Boekhandel to vc.com/case-studies

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#203]
Please add this new case study to the page: https://virtocommerce.com/case-studies
Make a new rectangle withe the Standaard Boekhandel Logo: 
![SBoekhandellogohorizontaal](https://user-images.githubusercontent.com/43222967/58440922-b1ea1780-8092-11e9-822c-07e4fb8b079a.png)
1) Add the heading in Red: RETAIL & DISTRIBUTION
2) Objective: Replatform for Flexible Ordering & Distribution
3) Create the summary: Online bookseller alignsed online & offline ordering and complex pricing to deliver a faster and more efficient ordering process

4) And create a new clickthrough page for it with this text:

And create the form that downloads this attached document:
[Standaard Boekhandel_Virto Commerce_Case Study_Final.pdf](https://github.com/VirtoCommerce/vc-content/files/3225062/Standaard.Boekhandel_Virto.Commerce_Case.Study_Final.pdf)

Title: Standaard Boekhandel Opens New Chapter on
Digital Commerce by Replatforming to Virto

Looking to strengthen its position in a fiercely competitive online book sales market, Standaard Boekhandel, Belgium's largest book retailer, embarked on a digital transformation process that was to deliver a best-in-class omnichannel customer experience. Competition in online book sales is fierce. Having the best product offering in books and the most user-friendly ordering site which links seamlessly to all your systems are basic but critical requirements for success.
Such an omnichannel experience requires a flexible and stable commerce platform capable of aligning online and offline ordering through integration with the cash registration systems, resulting in a faster and more efficient ordering process.

REPLATFORMING HELPED OVERCOME COMMERCE LIMITATIONS
Standaard Boekhandel chose to replatform to Virto Commerce in order to gain
capabilities they did not have on SAP Hybris so that they could extend their
product offering, integrate efficiently with different channels, and improve the
search functionality for their two brands. Because they were facing limitations
with their previous commerce tool, they wanted to migrate
to a more flexible and sustainable platform.

**Comment by tatarincev** [comment]
@blazemachine Could you take this issue in work?

**Comment by blazemachine** [comment]
Hello, @mpennie you may watch the result on the https://staging.virtocommerce.com/case-studies page and on the https://staging.virtocommerce.com/case-studies/standaard-boekhandel page.

**Comment by mpennie** [comment]
Thank you. Could you move the new Standaard Boekhandel rectangle to the top of this page, to the right of the Bosch content? https://staging.virtocommerce.com/case-studies

Also Please use this PDF attached in the download file (I made an edit). Thank you. 
[Standaard Boekhandel_Virto Commerce_Case Study_Final.pdf](https://github.com/VirtoCommerce/vc-content/files/3227970/Standaard.Boekhandel_Virto.Commerce_Case.Study_Final.pdf)

**Comment by blazemachine** [comment]
Done.

**Comment by mpennie** [comment]
Please fix my typo above in the description on this first page: in the word "aligned" - remove the "s":

Online bookseller aligned online & offline ordering and complex pricing to deliver a faster and more efficient ordering process.
https://staging.virtocommerce.com/case-studies

**Comment by blazemachine** [comment]
Fixed.

**Comment by mpennie** [comment]
Thanks. Please wait for final approval - Do not put on the live site yet. Thank you

**Comment by tatarincev** [comment]
@mpennie  somehow this case study was published with other changes, Should we remove it from publication?

**Comment by mpennie** [comment]
@Eugeny Tatarincev<mailto:et@virtoway.com> Yes – please do remove it from publication. We are still waiting on approval from the client. They have been delayed, so it makes me think there must be changes coming. Thank you.

**Comment by mpennie** [comment]
@tatarincev  @blazemachine 
[Virto Commerce Standaard Boekhandel Case Study.pdf](https://github.com/VirtoCommerce/vc-content/files/3342233/Virto.Commerce.Standaard.Boekhandel.Case.Study.pdf)
Please update the file with this PDF for download. Be sure the browser bar indicates the right file name. Thank you!

**Comment by mpennie** [comment]
I don't see Lavazza or Standaard Boekhandel up -- where did they go?

**Comment by tatarincev** [comment]
Published  https://virtocommerce.com/case-studies
