### ISSUE TITLE
Add to vc.com blog - Virto Version 3 Beta: Product Release Notes

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#215]
Please add to the virtocommerce.com/blog these "Virto Version 3 Beta: Product Release Notes"
[VC version 3 release notes.docx](https://github.com/VirtoCommerce/vc-content/files/3253074/VC.version.3.release.notes.docx)
![VERSION 3_blog post graphic](https://user-images.githubusercontent.com/43222967/58890680-f3388380-869f-11e9-989f-ff4f0fd2b3d4.png)

**Comment by blazemachine** [comment]
Published on the https://staging.virtocommerce.com/blog page.

**Comment by tatarincev** [comment]
Still on hold, @mpennie  let us known when this article will be ready for publish

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/blog/virto-version-3-beta-product-release-notes
