### ISSUE TITLE
Add new case study to https://virtocommerce.com/case-studies for Lavazza

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#216]
![Lavazza](https://user-images.githubusercontent.com/43222967/59171244-edef9480-8af6-11e9-81b3-6b909d40c149.jpeg)

Add new rectangle for LAVAZZA at top next to Bosch https://virtocommerce.com/case-studies
Use logo 
RETAILER & DISTRIBUTOR 
Objective: B2B & B2C Online Store Platform
**Created new, Unified ecommerce platform for B2B & B2C and gained insights into customer behavior**

THE CHALLENGE
Lavazza Nederland needed a new ecommerce platform because their current solution was outdated and no longer aligned with
the current or future goals. They needed to respond to both B2B and B2C customers' needs for a better online shopping
experience, personalized transactions, up-to-date customer insights, and product information.
The implementation was technically complex because other systems needed to link and integrate seamlessly across Lavaza's
ecosystem. Furthermore, the B2B and B2C activities had to be unified to streamline workflow and avoid managing multiple catalogs and duplicate work on the backend.
Lavazza searched for a robust and flexible ecommerce platform and selected Virto Commerce because it could handle this data integration, be deployed in multiple countries, and was both flexible and scalable.

"We chose Virto Commerce for Lavazza because it is the only ecommerce platform
that has the functionality, flexibility, and scalability we need -- today and long-term.
With Virto, the product options are customizable for both B2B and B2C activities -
and that improved customer ordering experiences and streamlined our processes." -- rb2 ecommerce team
[Virto Commerce Lavazza Case Study_v3.pdf](https://github.com/VirtoCommerce/vc-content/files/3302223/Virto.Commerce.Lavazza.Case.Study_v3.pdf)

**Comment by mpennie** [comment]
DRAFT - Please hold

**Comment by mpennie** [comment]
Hi - Go ahead and make it live please. If there are edits later, I will get back to you. Thank you.

**Comment by mpennie** [comment]
See new PDF -- please make it live.
[Virto Commerce Lavazza Case Study_v3.pdf](https://github.com/VirtoCommerce/vc-content/files/3302225/Virto.Commerce.Lavazza.Case.Study_v3.pdf)

**Comment by blazemachine** [comment]
Done. https://staging.virtocommerce.com/case-studies/lavazza

**Comment by mpennie** [comment]
It does not look like the PDF is downloading. Can you help?

**Comment by mpennie** [comment]
Hello @blazemachine  - would you please swap out the PDF file on the case study for this one attached
[Virto Commerce Lavazza Case Study_NL.pdf](https://github.com/VirtoCommerce/vc-content/files/3330896/Virto.Commerce.Lavazza.Case.Study_NL.pdf)
?
Thank you,
Megan

**Comment by tatarincev** [comment]
Published https://virtocommerce.com/case-studies/lavazza
