### ISSUE TITLE
Update tracking code and button type - virtocommerce.com/case-studies pages

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#220]
We need your help to 1) change the button code on the case study pages and 2) add a new tracking code to the https://virtocommerce.com/case-studies  pages – and all child pages. For example on: https://virtocommerce.com/case-studies/bosch and every page under case-studies. 
See below:

1. The tracking code needs to be replaced with the new one here: https://app.autopilo…ings/anywhere-tracking/website

2.  Important! The form's submit button needs to be changed to a format like this: <input type="submit"> This extra bit of info may be helpful for you too: It needs to work as a standard HTML form. You can still define custom onclick and onsubmit handlers to get client-side validation or any other events you want to happen when the form is submitted, it just needs to be in the form of a submit button.See more detail on the article here: https://support.autopilothq.com/hc/en-us/articles/204151389-Troubleshoot-a-form-that-isn-t-being-capturedTroubleshoot a form that isn't being captured
Note that this article is intended for those people who are technical and can modify their form code.

**Comment by mpennie** [comment]
the button type isn't allowing submissions of the form
https://cl.ly/67e207da0817

**Comment by tatarincev** [comment]
Published
