### ISSUE TITLE
Wrong title in PDF browser bar for Case Study - Lavazza

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#229]
Hello: the Lavazza PDF is tagged as Standard Bockhandel in the browser bar on the PDF: https://virtocommerce.com/assets/files/lavazza-case-study.pdf

Please edit this -- and the be sure to check and edit those in the future so they are correct for the PDF on each case study. Thank you.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
