### ISSUE TITLE
Missing Case Studies on https://virtocommerce.com/case-studies - Lavazza and Standaard Boekholden

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#230]
Our case studies Lavazza and Standaard Boekhandel are not on this page:
https://virtocommerce.com/case-studies

These pages are still live, which is good - but they have nothing pointing to it from main case study page: https://virtocommerce.com/case-studies/lavazza
https://virtocommerce.com/case-studies/standaard-boekhandel

Thank you. - Megan

**Comment by mpennie** [comment]
Please be sure to post the NEW file for download PDF for Standaard Boekhandel -- here it is: 
[Virto Commerce Standaard Boekhandel Case Study.pdf](https://github.com/VirtoCommerce/vc-content/files/3343754/Virto.Commerce.Standaard.Boekhandel.Case.Study.pdf)

**Comment by tatarincev** [comment]
Have been published https://virtocommerce.com/case-studies.
We unpublished these case-studies because your requested us to postpone. Now we have published them again.
