### ISSUE TITLE
New blog post: New Partner Director John Sekevitch: https://virtocommerce.com/blog/category/virtocommerce-news

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#233]
Hello - please add this as a blog post:
![image](https://user-images.githubusercontent.com/43222967/61235570-d2823580-a703-11e9-8a41-265c9c173da4.png)

![Blog post header JOHN S](https://user-images.githubusercontent.com/43222967/61235132-bc27aa00-a702-11e9-96d8-c9e26d65d373.png)

**Comment by tatarincev** [comment]
@blazemachine Please take this in work

**Comment by blazemachine** [comment]
@mpennie You may watch the result on the https://staging.virtocommerce.com/blog/new-partner-director-john-sekevitch page.

**Comment by mpennie** [comment]
Looks great. Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tatarincev** [comment]
Published  https://virtocommerce.com/blog/new-partner-director-john-sekevitch
