### ISSUE TITLE
Swap PDF on Case Study for Standaard Boekhandel

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#236]
Hello: Please swap the download PDF for the Standaard Boekhandel case study for this one. 
Thank you.
Megan
[Virto Commerce Standaard Boekhandel Case Study.pdf](https://github.com/VirtoCommerce/vc-content/files/3443653/Virto.Commerce.Standaard.Boekhandel.Case.Study.pdf)

**Comment by tatarincev** [comment]
Done
