### ISSUE TITLE
Redisign glossary

### ISSUE THREAD

**Issue by n2pro** [VirtoCommerce/vc-content#24]
Helpdesk Ticet: 7452
Redesign of the following pages in accordance with the layout:
- [x] /b2b-ecommerce-companies-websites
- [x] /best-ecommerce-platforms
- [x]  /what-is-b2b-ecommerce

**Comment by n2pro** [comment]
@AndrewYunisov available on [qc](https://vc-public-qc.azurewebsites.net) for verification.

**Comment by AndrewYunisov** [comment]
@n2pro , please change 2017 to 2018 at /glossary/best-ecommerce-platforms in all text items and meta tags. I forgot to mention that I changed it on the current website after we started this redesign.

**Comment by n2pro** [comment]
@AndrewYunisov fixed 2018

**Comment by AndrewYunisov** [comment]
@n2pro , good to go on production. Please, proceed.
