### ISSUE TITLE
Update "Enabling login within external providers" article

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-content#240]
It's about 3.5 year since the last update to https://virtocommerce.com/docs/vc2devguide/working-with-storefront/enabling-login-within-external-providers article. It was written for Storefront v2 and now we have v4. 
Resolutions: 
1. Mark the article as obsolete and tag as "v2" specific. And write a new article.
2. Just update the article to comply with the latest Storefront

**Comment by tatarincev** [comment]
@eMazeika Could you address all issue relies to virtocommerce.com site to V.Turovets and avoid of  registration these issues in GitHub repositories

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
