### ISSUE TITLE
Update platform-settings.md 2

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-content#241]
Need to update [platform-settings.md](https://github.com/VirtoCommerce/vc-content/blob/deploy/pages/docs/vc2devguide/deployment/platform-settings.md) as there is no other source to know the configuration options. There are new settings added since the last update (eg, SmsGateway, SuppressForcingCredentialsChange)

**Comment by tatarincev** [comment]
@eMazeika  How about do it yourself?

**Comment by eMazeika** [comment]
Thanks for the suggestion

**Comment by eMazeika** [comment]
#250

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
