### ISSUE TITLE
Add new VC.com Blog post

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#247]
Please add this content as a new post to the Virtocommerce.com/blog page. Thank you.

![image](https://user-images.githubusercontent.com/43222967/66430184-6d6e7100-e9ce-11e9-8693-4b59e532c67a.png)
![Blog post graphic Replatorming PR post](https://user-images.githubusercontent.com/43222967/66430198-765f4280-e9ce-11e9-90b9-a1fc9b03f677.png)

**Comment by blazemachine** [comment]
@mpennie Hi. We are not doing for virtocommerce.com tasks now.
