### ISSUE TITLE
Update module settings.md

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-content#248]
Update https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/managing-module-settings by adding section on "store-dependent settings": background, registration and sample code. Check "Lesson 3" take some content from it.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
