### ISSUE TITLE
Add GA event while clicking "Read case study" buttons 

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#28]
We need to track these clicks in GA using event tracking. Pages where buttons exist: 
- https://virtocommerce.com/glossary/best-ecommerce-platforms
- https://virtocommerce.com/glossary/b2b-ecommerce-companies-websites
- https://virtocommerce.com/glossary/what-is-b2b-ecommerce
- https://virtocommerce.com/case-studies
Please, add the GA event to all the buttons "Read case study" and "Read more case studies".

**Comment by Woland2k** [comment]
we should use segment to publish events, that way they are also available in CRM

**Comment by AndrewYunisov** [comment]
@Woland2k , I am not aware of how can this be done. Can you help, please?

**Comment by Woland2k** [comment]
Developer should know, here is one document describing how to do that: https://segment.com/blog/segment-tracking-plan/

**Comment by AndrewYunisov** [comment]
Issue is closed, because we decided to introduce the new functionality which makes pages appear while clicking these links.
