### ISSUE TITLE
Updates to /our-offers/cloud-ecommerce-platform

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#31]
1) insert the block "BEST CLOUD ECOMMERCE PLATFORM INTEGRATIONS"
Include the same apps as here - https://screencast.com/t/DhE7hC1n7X.
2) This block should be centered - https://screencast.com/t/tIXa3nn9mLmS. 
Add the text: CLOUD ECOMMERCE PLATFORM BUILT USING CUTTING-EDGE WEB TECHNOLOGIES
before it just like here - https://screencast.com/t/hi8uVMgYKs
3) Add the block "What experts are saying about our cloud platform?" below prices:
Here is the proposed design - https://screencast.com/t/l1z3XhwM1. 
Content: 
1. 5/5 Ecommerce-Platforms.com
"A Highly Advanced Cloud Ecommerce Platform For Serious Business"
https://ecommerce-platforms.com/articles/virtocommerce-review-highly-advanced-enterprise-ecommerce-platform-serious-business (link should be nofollow)
2. 5/5 Capterra.com
"Customizable great architecture - these guys knows what they do!"
https://www.capterra.com/p/147200/VirtoCommerce/ (link should be nofollow)
3. 5/5 G2Crowd.com
"The ease to build complex B2B scenarios, solutions for distributors and manufacturers."
https://www.g2crowd.com/products/virtocommerce/reviews (link should be nofollow)
4) Add video https://www.youtube.com/watch?v=22BMH86RQys to the right - https://screencast.com/t/CGECd7H65PLW.

**Comment by n2pro** [comment]
Updated this page [here](https://vc-public-qc.azurewebsites.net/vccom/our-offers/cloud-ecommerce-platform).
![image](https://user-images.githubusercontent.com/13115017/38940635-eed96368-432a-11e8-88d3-69bceddc6690.png)

**Comment by n2pro** [comment]
Fixed [this page.](https://vc-public-qc.azurewebsites.net/our-offers/cloud-ecommerce-platform)
![image](https://user-images.githubusercontent.com/13115017/38978946-28002af8-43b9-11e8-960c-fdaf93bc4865.png)

**Comment by AndrewYunisov** [comment]
Could be released.
