### ISSUE TITLE
Updates to /b2b-ecommerce

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#32]
1. Add the block "What experts are saying about our B2B ecommerce software?":
Here is the proposed design - https://screencast.com/t/l1z3XhwM1.
Content:
5/5 Ecommerce-Platforms.com
"A Highly Advanced B2B E-commerce Software For Serious Business"
https://ecommerce-platforms.com/articles/virtocommerce-review-highly-advanced-enterprise-ecommerce-platform-serious-business (link should be nofollow)
5/5 Capterra.com
"The best B2B ecommerce platform - these guys knows what they do!"
https://www.capterra.com/p/147200/VirtoCommerce/ (link should be nofollow)
5/5 G2Crowd.com
"The software to build complex B2B scenarios, solutions for distributors and manufacturers."
https://www.g2crowd.com/products/virtocommerce/reviews (link should be nofollow)

Please, place the block under integrations section on the grey background.

2. Add the breadcrumb to the footer like here - https://www.pepperi.com/b2b-e-commerce/.
https://screencast.com/t/Xbi2oZBUW

**Comment by n2pro** [comment]
@AndrewYunisov, @OlegoO   I offer bread crumbs in a separate ticket, since there are some difficulties with this.

**Comment by n2pro** [comment]
@AndrewYunisov footer is common for all pages, for one page it does not work. It is better to make a separate task

**Comment by AndrewYunisov** [comment]
Make it not in footer then, but in the last line of page template.

**Comment by n2pro** [comment]
Updated [this page](https://vc-public-qc.azurewebsites.net/b2b-ecommerce-platform)
![image](https://user-images.githubusercontent.com/13115017/39053855-5d5a0424-44b0-11e8-9156-70edf930bcd7.png)

**Comment by AndrewYunisov** [comment]
Can be released.
