### ISSUE TITLE
Updates to /

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#33]
1) Add the block "What experts are saying about our enterprise e-commerce platform?" before SEO text:
Here is the proposed design - https://screencast.com/t/l1z3XhwM1.
Content:
5/5 Ecommerce-Platforms.com
"A Highly Advanced Enterprise E-commerce Platform For Serious Business"
https://ecommerce-platforms.com/articles/virtocommerce-review-highly-advanced-enterprise-ecommerce-platform-serious-business (link should be nofollow)
5/5 Capterra.com
"The best enterprise ecommerce platform - these guys knows what they do!"
https://www.capterra.com/p/147200/VirtoCommerce/ (link should be nofollow)
5/5 G2Crowd.com
"The software to build complex enterprise ecommerce solutions and scenarios."
https://www.g2crowd.com/products/virtocommerce/reviews (link should be nofollow)

2) Add the reviews block under SEO text block. Design - https://screencast.com/t/4cGiVzsOgAt.
Content:

OUR CUSTOMERS ABOUT ENTERPRISE E-COMMERCE PLATFORM

KEVIN CORY
VP-Technology and Strategic 
Planning, GC Incentives
«The new enterprise ecommerce platform takes advantage of a lot of the latest thoughts on high performance, high quality software development. By adopting this Microsoft ecommerce software, we are adopting technologies that will allow us to better structure how we build the rest of our systems internally.»

SERGEY SINYUGIN
CEO Kupinatao Enterprise
«Using Virto Commerce platform capabilities we have created very powerful enterprise system of gathering, publication and managing customer reviews. This Microsoft ecommerce platform helps Kupinatao customers make the right choice out of millions of positions and drives our sales.»

OLGA LOMKO
Marketing Director Kitmall.ru
«Virto Commerce Microsoft .Net ecommerce software lets us reduce the number of people involved in management of product promotions from six to one. We don’t depend on IT guys anymore, and everybody benefits from this.»

**Comment by n2pro** [comment]
Updated [this page.](https://vc-public-qc.azurewebsites.net/)

**Comment by AndrewYunisov** [comment]
1) WHAT EXPERTS ARE SAYING ABOUT OUR B2B ECOMMERCE SOFTWARE?
 - I wrote that it should be called "What experts are saying about our enterprise e-commerce platform?"
2) Same with OUR B2B CUSTOMERS ABOUT THE PLATFORM. It should be called OUR CUSTOMERS ABOUT ENTERPRISE E-COMMERCE PLATFORM as per my comment below. 

Please, change this and upload to production.

**Comment by n2pro** [comment]
![image](https://user-images.githubusercontent.com/13115017/39052756-563bf056-44ad-11e8-8486-f311b4ecc5d5.png)

**Comment by AndrewYunisov** [comment]
Can be released.
