### ISSUE TITLE
Updates to /glossary/best-ecommerce-platforms

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#35]
1) There are multiple H2 tags on the page. We need to have single H2 here - https://screencast.com/t/r9dgsRxB8h. All the rest should be visually the same, but with no H2 in the code. 
2) Under the "BEST ECOMMERCE PLATFORM" please add "20 BEST E COMMERCE PLATFORM CONTENDERS" with the names of the platforms in the list with anchor links to them. 
3) Change title to: 
<title>20 best ecommerce platforms for websites in 2018. Top ecommerce platforms list</title>
4) Change H1 to: 
<h1 itemprop="headline" class="glosary-t">20 best ecommerce platforms for websites in April 2018. Top ecommerce platforms list</h1>
5) Change description to: 
<meta name="description" content="20 best ecommerce platforms for websites. 2018 top ecommerce platforms list. How to choose the best ecommerce platform for your business?" />
6) Change date to: Updated: April 17, 2018.

**Comment by n2pro** [comment]
Updated this page  [here](https://vc-public-qc.azurewebsites.net/glossary/best-ecommerce-platforms)
![image](https://user-images.githubusercontent.com/13115017/38937436-7df2cfba-4323-11e8-8609-4889688efcd4.png)

**Comment by AndrewYunisov** [comment]
2) Instead of orange buttons here - https://screencast.com/t/KDCg2wgJ just create the list of names with anchor links. Just a regular list on the white background.

**Comment by n2pro** [comment]
Fixed on list links.
![image](https://user-images.githubusercontent.com/13115017/38978121-be9dcf40-43b6-11e8-9758-eb1167f6a75c.png)

**Comment by AndrewYunisov** [comment]
1) CONTENDER -> CONTENDERS
2) Please center these 2 columns. 
Could be released after.

**Comment by n2pro** [comment]
Update [this page](https://vc-public-qc.azurewebsites.net/glossary/best-ecommerce-platforms)
![image](https://user-images.githubusercontent.com/13115017/39055367-595a317e-44b4-11e8-87b2-8c70a21b668a.png)

**Comment by AndrewYunisov** [comment]
Can be released.
