### ISSUE TITLE
Updates to /glossary/shopify-alternatives

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#36]
1) Switch the page to the new design template that we did with other pages
2) Change title to: 
<title>Top 10 Shopify alternatives in 2018. 10 best Shopify competitors.</title>
3) Change H1 to: 
<h1 itemprop="headline" class="title">Top 10 Shopify alternatives. 10 best Shopify competitors. The best alternatives to Shopify in 2018.</h1>
4) <meta name="description" content="Any ecommerce platform has the great support base, which offers you a wide variety of tools to alter your store. One of the best shopping cart platforms for an e-commerce website is Shopify, but there are some great Shopify alternatives and competitors that you should check out in 2018." />
5) please add "10 BEST SHOPIFY ALTERNATIVE CONTENDERS" block with the names of the platforms in the list with anchor links to them after the first banner

**Comment by n2pro** [comment]
The update page is available [here](https://vc-public-qc.azurewebsites.net/glossary/shopify-alternatives).
![image](https://user-images.githubusercontent.com/13115017/38925897-374b1026-4301-11e8-91ed-ee3db37ba038.png)

**Comment by n2pro** [comment]
@AndrewYunisov I do not understand. Could you imagine schematically

**Comment by n2pro** [comment]
Updated this page [here](https://vc-public-qc.azurewebsites.net/glossary/shopify-alternatives).

**Comment by AndrewYunisov** [comment]
Instead of orange buttons here - https://screencast.com/t/KDCg2wgJ just create the list of names with anchor links. Just a regular list on the white background.

**Comment by n2pro** [comment]
Fixed list links.
![image](https://user-images.githubusercontent.com/13115017/38978293-42c1dca8-43b7-11e8-9a63-d0503425c631.png)

**Comment by AndrewYunisov** [comment]
In this case should be aligned at left, please. Also the block title should be on grey background as others on the page.
Then could be released.

**Comment by n2pro** [comment]
Updated [this page.](https://vc-public-qc.azurewebsites.net/glossary/shopify-alternatives)

**Comment by AndrewYunisov** [comment]
OK, last one  - add numbers in this list, please. Example - https://screencast.com/t/zbb8blmMVn

**Comment by n2pro** [comment]
Updated [this page.](https://vc-public-qc.azurewebsites.net/glossary/shopify-alternatives)
![image](https://user-images.githubusercontent.com/13115017/39052236-a6709c40-44ab-11e8-98ec-6f2ba4ffd8d4.png)

**Comment by AndrewYunisov** [comment]
Can be released.
