### ISSUE TITLE
update vc-community blocks

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#37]
Reorganize positions of blocks:
1. COMMUNITY RESOURCES
2. BECOME A CONTRIBUTOR
3. COMMUNITY SUPPORT (add new block)
4. GET COMMUNITY LICENSE
5. ADD APP TO MARKETPLACE

COMMUNITY RESOURCES
* Documentation (/docs)
** Getting Started (/docs/vc2devguide/getting-started)
** Lessons (/docs/lessons)
* Roadmap
* Github repositories structure (https://github.com/VirtoCommerce/)
** VirtoCommerce Platform repository (https://github.com/VirtoCommerce/vc-platform)
** VirtoCommerce Storefront for ASP.NET repository (https://github.com/VirtoCommerce/vc-storefront)
** VirtoCommerce Storefront for ASP.NET Core 2.0 repository (https://github.com/VirtoCommerce/vc-storefront-core)

COMMUNITY SUPPORT
 Stackoverflow channel
 Gitter channel
 Github issues (https://github.com/VirtoCommerce/vc-platform/issues)

**Comment by n2pro** [comment]
Added [new block ](https://vc-public-qc.azurewebsites.net/vc-community)to the community.
