### ISSUE TITLE
mobile menu doesn't have getting started menu

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#40]
As a customer, I want to see same menu on desktop, tablet and mobile view.
![image.png](https://images.zenhubusercontent.com/58e3abe551aa2c30577a5813/fae57f02-bb1e-46e4-bb3a-9909f3e3bd20)
![image.png](https://images.zenhubusercontent.com/58e3abe551aa2c30577a5813/bbf54074-0c7a-45b1-b5e2-b860dd06d043)

**Comment by n2pro** [comment]
The updated menu is available [here ](https://staging.virtocommerce.com/)
![image](https://user-images.githubusercontent.com/13115017/38917195-4902190c-42ea-11e8-9b33-19a2b7593288.png)

**Comment by OlegoO** [comment]
@Woland2k  @n2pro Now, mobile menu is configurable via Link list
![image](https://user-images.githubusercontent.com/7639413/38916570-3d94bdce-42e8-11e8-934c-06bb96578867.png)
![image](https://user-images.githubusercontent.com/7639413/38919384-b77d382a-42f0-11e8-839b-276f88a8d70f.png)

To be consistent, I will create a new ticket to move all menu to link list
