### ISSUE TITLE
Uncaught ReferenceError: openContactUs is not defined

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#41]
JavaScript error "Uncaught ReferenceError: openContactUs is not defined" is occured if click "Getting Started"  on docs, blogs, glossary, guides and tilda pages

Example:
https://virtocommerce.com/blog
https://virtocommerce.com/blog/way-you-manage-product-information-is-affecting-your-sales
https://virtocommerce.com/docs
https://virtocommerce.com/docs/lessons
https://virtocommerce.com/glossary

**Comment by n2pro** [comment]
Fixed getting start dialog on these pages.
