### ISSUE TITLE
Download case study pages

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#45]
Hi all,
We need to create a page for each case study in the section https://virtocommerce.com/case-studies. The button will lead not to PDF, but to a separate page of the website. Here is the design - https://yadi.sk/d/AQCC9hGv3Ug573 of a single page. As a top picture we take the website screenshot (customer's website), as a text - 1st paragraph from the case study (I can fix before the release if something will be done wrong). The form at the right needs to have email validation and send data to our CRM - FreshSales.

**Comment by AndrewYunisov** [comment]
Please, also include the customer quote before the text (not done in the design, late fix from e@). 
Should be: 
“We are a fast growing business, so we need a platform that would not only
allow us to expand, but also keep up with the ever growing needs and demands
of our sales strategies. Virto Commerce definitely ticks those boxes
being easily scalable and extremely flexible. By switching to this solution, we
are adopting technologies that will allow us to add new channels easily and
customize the product catalog for each of them, while keeping track of the
overall sales and assortment.”. - Andreas Kardell, CTO at Proffsmagasinet.se.

**Comment by n2pro** [comment]
@AndrewYunisov  What should happen when you click "download case study"?

**Comment by AndrewYunisov** [comment]
Well, if he has filled the form - he needs to go to the PDF file.

**Comment by n2pro** [comment]
@AndrewYunisov what do we do with the data?

**Comment by AndrewYunisov** [comment]
We will put it into AUtopilot, I will do it later.

**Comment by n2pro** [comment]
Added pages for case study, [this](https://vc-public-qc.azurewebsites.net/case-studies/proffsmagasinet) and for other pages.
![screenshot_7](https://user-images.githubusercontent.com/13115017/40310661-cf6fb480-5d0d-11e8-9037-b2d5cad42e0d.png)

**Comment by AndrewYunisov** [comment]
1) Отступ от картинки надо увеличить - https://screencast.com/t/rSr1WCrlxcw
2) Вторая кавычка в цитате отсутствует. 
3) Давайте назовем кнопку Download Full Case Study.

**Comment by n2pro** [comment]
Fixed
![image](https://user-images.githubusercontent.com/13115017/40347393-6a0cc216-5da0-11e8-9345-5a663829f3a3.png)

**Comment by AndrewYunisov** [comment]
PROFFMAGASINET -> PROFF**S**MAGASINET
I will ask Evgeny to approve and then will follow up to release.

**Comment by n2pro** [comment]
Fixed, after approve we can update.

**Comment by AndrewYunisov** [comment]
![shutterstock_512482957](https://user-images.githubusercontent.com/27814609/40529648-8c7319b2-5ffe-11e8-9527-221773034381.jpg)
![shutterstock_546307054](https://user-images.githubusercontent.com/27814609/40529649-8ca0cfce-5ffe-11e8-8ec8-3e085196ebe2.jpg)
Let's try to create 2 pages with different background, we need to try.
Please do.

**Comment by n2pro** [comment]
Different backgrounds for pages: 
https://vc-public-qc.azurewebsites.net/case-studies/proffsmagasinet
https://vc-public-qc.azurewebsites.net/case-studies/proffsmagasinet1
https://vc-public-qc.azurewebsites.net/case-studies/proffsmagasinet2

**Comment by n2pro** [comment]
The image will always be cropped, you provided images in 4:3 format, for this effect it is preferable to use 16:9.
The height of the block is 340 pixels, depending on the width - it is scaled.

**Comment by AndrewYunisov** [comment]
Evgeny and I decided to stay with the initial version with website screenshot. We need to fix the mobile page also: 
![microsoftteams-image](https://user-images.githubusercontent.com/27814609/41413393-3d4e1892-6fe3-11e8-8350-a99c402f102a.png)
Then we can create the other pages by analogue (I can fix the content if needed) and proceed to release. 
Please, go on.

**Comment by n2pro** [comment]
@AndrewYunisov  Can you see all the [other pages](https://vc-public-qc.azurewebsites.net/case-studies) and write comments except for mobile view?

**Comment by AndrewYunisov** [comment]
@n2pro , please: 
1) https://vc-public-qc.azurewebsites.net/case-studies/belysningsdesign 
Remove the 1st paragraph - https://screencast.com/t/vc2NO3Ddt
2) Finalize with mobile and we can go ahead.

**Comment by n2pro** [comment]
Remarks corrected!

**Comment by AndrewYunisov** [comment]
Can you, please add GA event to Download button on all pages? 
ga('send', 'event', 'Download', 'CaseStudy', '{case_name}');
case_name should be changed to the name of case page.

**Comment by AndrewYunisov** [comment]
Then we can release.

**Comment by n2pro** [comment]
where can I see an example on our website?

**Comment by AndrewYunisov** [comment]
I think we added the events to banners in glossary pages with you.

**Comment by Woland2k** [comment]
We should use segment events instead of adding GA. That way we can tie those to users in CRM.

**Comment by n2pro** [comment]
Added GA event for the case study, ready for release!

**Comment by AndrewYunisov** [comment]
Pls, release. I will work on Segment event later on in another task.

**Comment by AndrewYunisov** [comment]
What email are these forms sending to?

**Comment by n2pro** [comment]
Form data is not sent anywhere.
**n2pro:** @AndrewYunisov What should happen when you click "download case study"?
**AndrewYunisovWell**:  if he has filled the form - he needs to go to the PDF file.
**n2pro:** @AndrewYunisov what do we do with the data?
**AndrewYunisovWell**: We will put it into AUtopilot, I will do it later.

**Comment by AndrewYunisov** [comment]
Yes, I am putting it into Autopilot already. However, we might need email notifications as we're still defining how to deal with these guys. So, please:
1. Send email notification to sales@virtocommerce.com
2. Send the data into FreshSales
3. Add GDPR ticks to these pages

**Comment by Woland2k** [comment]
You don't send data directly to freshsales, it goes to segment first.

**Comment by n2pro** [comment]
@AndrewYunisov

**Comment by AndrewYunisov** [comment]
@n2pro , please pass the changes on qc to production.

**Comment by n2pro** [comment]
![image](https://user-images.githubusercontent.com/13115017/41723055-69886de0-756a-11e8-96fc-53ad3d137093.png)

**Comment by AndrewYunisov** [comment]
Release

**Comment by n2pro** [comment]
Done
