### ISSUE TITLE
Getting started fix + event for Segment / GA

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#46]
Getting started can't be clicked on Mac Chrome - https://screencast.com/t/WAVDHebQR.
Please, when fixing also add the event on this button.

**Comment by n2pro** [comment]
I use browserstack service, getting started working on Mac Chrome. You can see it [here](http://recordit.co/anSbuS5frv). 
This message just says that the player is not installed.
