### ISSUE TITLE
correct picture in "Blades and navigation"

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-content#48]
I expect to see 3 blades image for "3 blades: parent and a child blade having another child."
Now something ancient is displayed:

![image](https://user-images.githubusercontent.com/5801549/39441599-7853b738-4c7c-11e8-8c17-eb5fa66ec331.png)

**Comment by n2pro** [comment]
![image](https://user-images.githubusercontent.com/13115017/40826866-435a7594-657c-11e8-9b12-4771c59bb960.png)
