### ISSUE TITLE
Text fixes for / and /b2b-ecommerce-platform (expert quotes section)

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#49]
For main page:
1) "A Highly Advanced Cloud Ecommerce Platform For Serious Business" -> "A Highly Advanced Enterprise Microsoft E-commerce Platform For Serious Business"
2) "A Highly Advanced Cloud Ecommerce Platform For Serious Business" -> "The best enterprise e-commerce platform based on Microsoft - these guys knows what they do!"
For B2B page:
1) "A Highly Advanced Cloud Ecommerce Platform For Serious Business" -> "A Highly Advanced B2B Ecommerce Platform For Serious Business"
2) "A Highly Advanced Cloud Ecommerce Platform For Serious Business" -> "The best B2B e-commerce software - these guys knows what they do!"

**Comment by n2pro** [comment]
Index page
![image](https://user-images.githubusercontent.com/13115017/40226841-1e4e7b14-5a8d-11e8-90a1-9daa628516d0.png)
B2B page
![image](https://user-images.githubusercontent.com/13115017/40226863-2f524652-5a8d-11e8-96de-51282ab8ff11.png)
