### ISSUE TITLE
404 errors increase

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#51]
Google Webmaster Tools has shown an increase in 404 errors. Please, look at the attached list and fix the errors. 

[virtocommerce-com_20180508T090347Z_CrawlErrors.csv.zip](https://github.com/VirtoCommerce/vc-content/files/1983139/virtocommerce-com_20180508T090347Z_CrawlErrors.csv.zip)

Either fix the broken URL, or redirect to main.

**Comment by n2pro** [comment]
I fixed most of the links, I need to keep track of errors using пoogle цebmaster tools and azure application inside.

**Comment by AndrewYunisov** [comment]
Sending the latest lists with errors, please mark what was fixed.

[Архив.zip](https://github.com/VirtoCommerce/vc-content/files/2064761/default.zip)

**Comment by n2pro** [comment]
[Here ](https://github.com/VirtoCommerce/vc-content/blob/deploy/IISUrlRewrite.xml#L182)are all the redirects.
We also look forward to updating the platform for fixing bugs in / blog.
I would like to see the  count 404 for a particular url, since 404 is a normal response to an unknown request.
