### ISSUE TITLE
Maps not working

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#52]
https://virtocommerce.com/about-us
Карты поехали

**Comment by n2pro** [comment]
@AndrewYunisov I need a key!
To get it, go to [step 3](https://developers.google.com/maps/documentation/javascript/adding-a-google-map).

**Comment by AndrewYunisov** [comment]
This should be done by the account owner. 
@Woland2k , please do it from your account.

**Comment by OlegoO** [comment]
@dimitri-ak Could you create key?

**Comment by n2pro** [comment]
![image](https://user-images.githubusercontent.com/13115017/40837554-1d048fbe-659b-11e8-843a-de2e6924ea76.png)

**Comment by AndrewYunisov** [comment]
We need to release this ASAP. Looks OK to me.
