### ISSUE TITLE
Form fixes for GDPR

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#54]
In all website forms before the main button we should have the text: 
By clicking «{button name}» I agree to the Virto Commerce [Terms](https://virtocommerce.com/terms) and [Privacy](https://virtocommerce.com/privacy). 
Just like here - https://www.baculasystems.com/download-kickstart-standalone-trial-version.

**Comment by AndrewYunisov** [comment]
This is a critical task from Eugeny Grigul.

**Comment by n2pro** [comment]
Added to all forms. Can be seen on [qc.](https://vc-public-qc.azurewebsites.net/contact-us).
After approving all changes that are on QC, we can update the main site.

**Comment by AndrewYunisov** [comment]
Approved.

**Comment by AndrewYunisov** [comment]
21 is not mine, 45 is still not approved. Everything else is good to go.

**Comment by n2pro** [comment]
Ok, awaiting approval #45 and update the main site.

**Comment by n2pro** [comment]
Yes, I'll do it tomorrow.
It is necessary that the tasks do not hang in the air.
