### ISSUE TITLE
As a content manager, I want to edit cms page in own repository 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-content#56]
As a content manager, I want to create, edit cms page
GIVEN https://github.com/VirtoCommerce/vc-content-pages repository
WHEN I edit page in the MASTER branch
AND I commit update
THEN the vc-content-pagesshould be updated page on production environment (PROD and STAGE slots)
Acceptance criteria:
MASTER is default branch

As a content manager, I want to receive email notification when new contents are available for test
GIVEN https://github.com/proffsmagasinet/pm-cms-content-pages repository
WHEN I edit page in the MASTER branch
AND I commit update
THEN the vc-content-pages should be updated page on production environment (PROD and STAGE slots)

As a developer, I want to create, edit cms page on STAGING environment
GIVEN https://github.com/VirtoCommerce/vc-content-pages repository
WHEN I edit page in the STAGING branch
AND I commit update
THEN the vc-content-pages should be updated page on STAGING environment

As a developer, I want to create, edit cms page on DEV environment
GIVEN https://github.com/VirtoCommerce/vc-content-pages repository
WHEN I edit page in the DEV branch
AND I commit update
THEN the vc-content-pages should be updated page on DEV environment

**Comment by tatarincev** [comment]
This issue may be no longer relevant because of https://github.com/VirtoCommerce/vc-cms-page-designer
