### ISSUE TITLE
GDPR fixes #2

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#57]
1. Cookies consent on website. Such text should appear on the website "We use cookies to provide best web experience for our users. By continuing to browse this site, you agree to this use. Read more from our Privacy Policy". Last one is a link to the page https://virtocommerce.com/privacy. 
I hope you saw many examples of such popups. I would suggest something like this - https://s3.envato.com/files/247784180/11-weepie-cookie-allow-front-bar-bottom-replacement-block.png with a correction to our color (grey). 
2. Near newsletter subscription add such notice "By submitting my email I agree to the Virto Commerce Terms and Privacy." (with links).

**Comment by n2pro** [comment]
Will be done after updating storefront-core to core 2.1

**Comment by AndrewYunisov** [comment]
@n2pro , @OlegoO - this is a very urgent fix as we're running out of the european law. 
You decide, but if we get fines they will be huge.

**Comment by AndrewYunisov** [comment]
Privacy policy attached.
[Virto Commerce Privacy Policy_20180606_v5_RJ_final.docx](https://github.com/VirtoCommerce/vc-content/files/2079301/Virto.Commerce.Privacy.Policy_20180606_v5_RJ_final.docx)

**Comment by n2pro** [comment]
Added cookies informer, you can see [this](https://vc-public-qc.azurewebsites.net/).
![image](https://user-images.githubusercontent.com/13115017/41094773-bbfb9eec-6a4f-11e8-9d18-a7fcfbd81c83.png)

**Comment by AndrewYunisov** [comment]
Good. Please , update the policy and release to the website. The other task #2 is also needed.

**Comment by n2pro** [comment]
I understand it is necessary to update the policy from the document?

**Comment by n2pro** [comment]
![image](https://user-images.githubusercontent.com/13115017/41096318-8adb992a-6a54-11e8-83be-214dbdd35d03.png)

**Comment by AndrewYunisov** [comment]
https://virtocommerce.com/account/invite
THis form also should contain 
By clicking «Sign In» I agree to the Virto Commerce Terms and Privacy.

**Comment by n2pro** [comment]
Updated [privacy page](https://vc-public-qc.azurewebsites.net/)

**Comment by AndrewYunisov** [comment]
Good to go.

**Comment by n2pro** [comment]
Done
