### ISSUE TITLE
GDPR #3

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#58]
Please, add the regular tick below the form at https://virtocommerce.com/jobs on all the apply forms. Forgot them.

**Comment by n2pro** [comment]
Fixed
![image](https://user-images.githubusercontent.com/13115017/41593478-7d0f4484-73c0-11e8-9fbb-82b060d215ef.png)

**Comment by AndrewYunisov** [comment]
Please, release ASAP.
