### ISSUE TITLE
Enterprise eCommerce page fixes

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#60]
https://virtocommerce.com/download-enterprise-whitepaper
1. URL should be https://virtocommerce.com/enterprise-ecommerce-whitepaper
Old URL should redirect to the new one with 301.
2. H1 should be "Enterprise Ecommerce Whitepaper" 
3. This should be H2 - https://screencast.com/t/dZOfqNPr2r9N
4. CLOUD ECOMMERCE PLATFORM BUILT USING CUTTING-EDGE WEB TECHNOLOGIES -> ENTERPRISE ECOMMERCE PLATFORM BUILT USING CUTTING-EDGE WEB TECHNOLOGIES 
5. esentially -> essentially
https://virtocommerce.com/our-offers/enterprise-edition 
1. URL should be https://virtocommerce.com/our-offers/enterprise-ecommerce-platform 
Old URL should redirect to the new one with 301.
2. H1 should be "Enterprise E-commerce Platform" 
3. Title should be "Enterprise e-commerce platform by Virto Commerce"
4. Enterprise Edition Advantages -> Enterprise E-commerce Platform Advantages
5. CLOUD ECOMMERCE PLATFORM BUILT USING CUTTING-EDGE WEB TECHNOLOGIES -> ENTERPRISE ECOMMERCE PLATFORM BUILT USING CUTTING-EDGE WEB TECHNOLOGIES

**Comment by Tilesto** [comment]
@AndrewYunisov, fixed on [staging.virtocommerce.com](https://staging.virtocommerce.com).

**Comment by AndrewYunisov** [comment]
@Tilesto , 
8) The current title is <title>Virto commerce - Enterprise e-commerce platform by Virto Commerce</title>. Need to fix. 
Other than that - ready for merging.
