### ISSUE TITLE
Segment Integration to Fresh Sales not working

### ISSUE THREAD

**Issue by virtogarren** [VirtoCommerce/vc-content#65]
Previously, we had an integration to FreshSales from Segment.  

This integration is not working anymore and needs to be fixed.

**Comment by Woland2k** [comment]
This was the fix: https://github.com/VirtoCommerce/vc-content/commit/ca8ad66c27ca9493ff62b18f0dc718b793657e2e, please make sure it is working next time (it can't really be tested on staging site since forms are not submitted on staging due to autopilot, only in production)

**Comment by n2pro** [comment]
@Woland2k we can not use the global form interceptor, because it violates the functionality for other forms, as well as logging in, inviting

**Comment by Woland2k** [comment]
@n2pro We need to log all activities, including logging in.

**Comment by Woland2k** [comment]
@tatarincev I can publish them, but I'm not sure how it affect login screen (login doesn't seem to work at all now, check https://github.com/VirtoCommerce/vc-content/issues/67)

**Comment by tatarincev** [comment]
Sure it won't be work, because you've handled submits for all forms, I think that if you continue the event propagation instead of swallow it will fix the problem. Does anybody have any idea why this integration stopped working?

**Comment by Woland2k** [comment]
@tatarincev login/logout doesn't work without any changes done, i haven't changed anything

**Comment by tatarincev** [comment]
Done, @Woland2k @AndrewYunisov  please check

**Comment by Woland2k** [comment]
looks like it is working
