### ISSUE TITLE
Update Customers Page

### ISSUE THREAD

**Issue by virtogarren** [VirtoCommerce/vc-content#66]
Please update the customer page to include only the logos attached to this ticket

![image9](https://user-images.githubusercontent.com/31021659/43789596-62bd0e32-9a3e-11e8-8556-6d95bc7545ce.png)
![image10](https://user-images.githubusercontent.com/31021659/43789597-62cb6946-9a3e-11e8-8146-4292fa7fa81a.png)
![image11](https://user-images.githubusercontent.com/31021659/43789598-62da0cda-9a3e-11e8-8f1c-a240f4ae484c.png)
![image12](https://user-images.githubusercontent.com/31021659/43789599-62e8147e-9a3e-11e8-8ae7-06fdea5c4532.jpeg)
![image13](https://user-images.githubusercontent.com/31021659/43789600-62f63446-9a3e-11e8-988b-9de19278a9af.png)
![image15](https://user-images.githubusercontent.com/31021659/43789601-6304a774-9a3e-11e8-9244-daba6004e325.png)
![image16](https://user-images.githubusercontent.com/31021659/43789602-631198da-9a3e-11e8-98f7-c353636fcd7e.jpg)
![image17](https://user-images.githubusercontent.com/31021659/43789603-63232fbe-9a3e-11e8-8631-41992e4aa9e3.png)
![image18](https://user-images.githubusercontent.com/31021659/43789604-6333aa74-9a3e-11e8-88e7-495496e29ae3.png)
![image19](https://user-images.githubusercontent.com/31021659/43789606-6340a04e-9a3e-11e8-8514-3153eabcda39.png)
![image20](https://user-images.githubusercontent.com/31021659/43789607-634d6432-9a3e-11e8-9b8e-80675e406305.png)
![image21](https://user-images.githubusercontent.com/31021659/43789608-635b74a0-9a3e-11e8-8de7-128241d867ac.png)
![image22](https://user-images.githubusercontent.com/31021659/43789609-636a9642-9a3e-11e8-823b-692b7f41232f.png)
![image23](https://user-images.githubusercontent.com/31021659/43789610-6377164c-9a3e-11e8-9613-fe8b2000999d.png)
![image24](https://user-images.githubusercontent.com/31021659/43789611-6383f646-9a3e-11e8-8566-e0a7b2cfb626.png)

**Comment by AndrewYunisov** [comment]
Team: @OlegoO, @n2pro , @Tilesto - please update https://virtocommerce.com/customers. 
@virtogarren , should we also update the main page logos? I would do it if we have the approval.

**Comment by virtogarren** [comment]
Hey @AndrewYunisov, yes I agree we should update the main page logos. 

Please use:
Country Malt Group
Heineken
Bosch
Vivint.SmartHome
Rainbow Sandals

**Comment by tatarincev** [comment]
@AndrewYunisov Could you approve these changes on the staging?

**Comment by AndrewYunisov** [comment]
@tatarincev , I see no changes on https://staging.virtocommerce.com/customers. Where should I go?

**Comment by tatarincev** [comment]
@AndrewYunisov  It is already on production :) Just need to update staging then.

**Comment by virtogarren** [comment]
@AndrewYunisov we need to remove rainbow and Heineken from our client list for now.  We added them prematurely.  Please instead use Trendmark and Volvo for the homepage and just remove rainbow and Heineken from the clients' page, please.

**Comment by AndrewYunisov** [comment]
@OlegoO , please advice who is the right person to assign this.

**Comment by tatarincev** [comment]
@Tilesto, could you take a look at this issue?

**Comment by Tilesto** [comment]
@tatarincev ok, np)

**Comment by tatarincev** [comment]
Done

**Comment by virtogarren** [comment]
@AndrewYunisov @tatarincev @Tilesto thank you
