### ISSUE TITLE
Community sign out doesn't work

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-content#67]
When going to this page: https://virtocommerce.com/vc-community even when anonymous, you are always sign in and clicking sign out doesn't have any affect.

![image](https://user-images.githubusercontent.com/1566470/43794418-048074d6-9a33-11e8-96a8-7e2e61cf7ff5.png)

**Comment by tatarincev** [comment]
This игп occurs because all users in the storefront are registered in terms of the ASP.NET authentication system, and this Auth policy will return always true. So I'm going to fix this policy, will check another user flag in order to determine if the user is registered or not

**Comment by Woland2k** [comment]
@tatarincev  can we get this fixed as soon as possible since currently there is no login or registration required to get to a demo

**Comment by tatarincev** [comment]
@Woland2k @AndrewYunisov Done, please check
