### ISSUE TITLE
Redesign "List-of-Partners" Page

### ISSUE THREAD

**Issue by virtogarren** [VirtoCommerce/vc-content#72]
As part of our new initiative to build up our partner program, I would like a redesign of our partner's list page (/partners/list-of-partners).

The goal is to help users sort/filter our partners by region, expertise, and industry.

https://www.kentico.com/partners/solution-partners <- I want the page's layout/UX to be exactly like this, but with our branding.

**Comment by virtogarren** [comment]
As part of our new initiative to build up our partner program,  I would like a redesign of our partner's list page (/partners/list-of-partners).  

The goal is to help users sort/filter our partners by region, expertise, and industry. 

https://www.kentico.com/partners/solution-partners  <-  I want the page's layout/UX to be exactly like this, but with our branding.

**Comment by AndrewYunisov** [comment]
@virtogarren and @egrigul, I will take care of this.

**Comment by AndrewYunisov** [comment]
![img_20180903_162027_497](https://user-images.githubusercontent.com/27814609/44998449-7bc5ae80-afbe-11e8-930e-ece2de6a013d.jpg)
@virtogarren, we need to define what we do with some content items that were taken from Kentico.

**Comment by virtogarren** [comment]
@AndrewYunisov  here is some of my thoughts, @egrigul  or @Woland2k  you have any thoughts?
![untitled-1](https://user-images.githubusercontent.com/31021659/45048964-3b604200-b04b-11e8-82cc-d25d7f122906.png)

**Comment by virtogarren** [comment]
Here are some more requested changes.  After this, we're ready to go to HTML.

Here is the link to the partner badge designs in the OneDrive Marketing folder: "VirtoWay\VirtoCommerce - Documents\Marketing\Assets\partnerBadges.ai"

![partnergrid](https://user-images.githubusercontent.com/31021659/45116975-5782e280-b122-11e8-9e8e-63e25a055907.png)

**Comment by AndrewYunisov** [comment]
![partners](https://user-images.githubusercontent.com/27814609/45162641-19a3be00-b1f7-11e8-89c5-2b216bf0abfc.jpg)

**Comment by AndrewYunisov** [comment]
@virtogarren , let me know of this works and I'll upload source files.

**Comment by virtogarren** [comment]
Unless @Woland2k  or @egrigul  have comments, I'm happy with the result.

**Comment by virtogarren** [comment]
@AndrewYunisov , For the final production version, here is the proper level for each partner's badge. 

- Niteco - Silver
- Wipcore - Silver 
- Making Waves - Bronze
- Delaware - Silver
- JBS - Gold
- Bambit - Bronze

**Comment by AndrewYunisov** [comment]
[virto_partners.zip](https://github.com/VirtoCommerce/vc-content/files/2358032/virto_partners.zip)
@virtogarren , here is the final version with PSD and the fixes in badges.

**Comment by virtogarren** [comment]
@AndrewYunisov  looks great, my only concern is, are you planning on adding filters at the top for customers to use with the tags?  On the design we have tags, but really no way for the user to interact with those, is that something the devs will add?

**Comment by AndrewYunisov** [comment]
Should be done by them, yep. We'll fix that if they won't get it from the start ;)

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
