### ISSUE TITLE
Documentation site javascript error

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-content#81]
When opening documentation site javascript error is generated which prevents the page from loading completely.

![image](https://user-images.githubusercontent.com/1566470/46895944-7fefb200-ce2f-11e8-868f-b1afb6760b9c.png)

**Comment by Woland2k** [comment]
Fixed the immediate issue, however it displays empty user now. Need a more permanent fix.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
