### ISSUE TITLE
Add to VirtoCommerce.com Partner page content

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#85]
Hello: Would you please add this new content for the Partners page:  https://virtocommerce.com/partners/list-of-partners
---
NTARA LOGO 
United States
Founded in 1999, Ntara is a full-service digital agency specializing in commerce solutions within three verticals: branded manufacturing & distribution, healthcare & institutions, and high technology.
Contact: connect@ntara.com

---

FORTE DIGITAL (logo attached)
![forte_logo_sign_text_black](https://user-images.githubusercontent.com/43222967/47319340-470bc600-d603-11e8-8b6a-af98f333a3e6.png)
Markets: Norway, Sweden, Denmark, UK, Switzerland, Poland 
Languages Spoken: English, Swedish, Norwegian, Polish

Forte_Digital is an innovative software consulting company. Our group of experts has significant business understanding and deep experience. We provide advisory, user experience, development and integration services to our international customers. We work with startups and well-established businesses to help them with their digital business. Our main solution areas are B2C and B2B e-commerce platforms and dedicated digital products and services. We employ 40 consultants located in offices in Oslo, Norway and Kraków, Poland.
 
Contact: dawid@fortedigital.no

[Ntara_Mark_Blue.pdf](https://github.com/VirtoCommerce/vc-content/files/2503408/Ntara_Mark_Blue.pdf)

**Comment by tatarincev** [comment]
@Tilesto  could you take it?

**Comment by Tilesto** [comment]
@tatarincev I didn't even have time to answer xDD Ok, np)

**Comment by mpennie** [comment]
Hello! Would you let me know when you can do this? The partner company is pushing us for a date. Thank you.

**Comment by Tilesto** [comment]
@mpennie done) Check it here, please)
https://virtocommerce.com/partners/list-of-partners
