### ISSUE TITLE
Add to Customer Case Study page

### ISSUE THREAD

**Issue by mpennie** [VirtoCommerce/vc-content#92]
### Bosch success story
Bosch Gains Customer Insights and Builds Customer Loyalty Through New eCommerce Solution

> "We chose Virto Commerce because it is the only platform that had the customizability and support options that we need. 
From pre-service consultation to technical team support, Virto Commerce was responsive and informative, and most importantly, able to provide valuable insight into our core needs.”  
~ Cornelius Munz, BOSCH Digital 

**CHALLENGE**
Bosch Thermotechnik traditionally did not sell to the end customer, and instead they relied on their distribution channels for that final sale. That approach, however, did not allow Bosch to have any insight into their customers, their behavior, what products they chose, or how they were using them. 

**SOLUTION**
Bosch sought a digital solution to automate the information capture and build customer loyalty as well.

> To gain visibility into end customers, Bosch wanted to build a Customer Loyalty program, with points-based purchasing and 14,000+ catalogue items, and selected Virto Commerce to create their eCommerce solution.
 
Read the whole story.
[Bosch Case Study_Final.pdf](https://github.com/VirtoCommerce/vc-content/files/2550812/Bosch.Case.Study_Final.pdf)

{% include 'case-study-download', downloadUrl: "../assets/files/sd-case-study.pdf", caseName: "bosch" %}

**Comment by mpennie** [comment]
Hello team: @tatarincev 
Would you please 1) add the content for BOSCH that I added on the customer case study page (https://virtocommerce.com/case-studies) and have it click through to the below new page.
2) Add a New page for the Bosch case study with this content above, and the form that all the case study pages have to download the link. (I will connect the contact info to capture it in Autopilot when you are finished.) The download file is attached above. 

Please let me know if you have questions. Thank you!

**Comment by mpennie** [comment]
@blazemachine Hi Segey - let me know if you have questions. Thanks, Megan

**Comment by tatarincev** [comment]
We will start work on this task tomorrow 07.11.2018. All seems clear and I guess we can delivery this case study on this week

**Comment by tatarincev** [comment]
Done please check https://virtocommerce.com/case-studies/bosch
