### ISSUE TITLE
New glossary page for conversational commerce

### ISSUE THREAD

**Issue by AndrewYunisov** [VirtoCommerce/vc-content#99]
Here is the example glossary page - https://virtocommerce.com/glossary/b2b-ecommerce-companies-websites. 
[A Simple Look at the Key Components of Conversational Commerce.docx](https://github.com/VirtoCommerce/vc-content/files/2600759/A.Simple.Look.at.the.Key.Components.of.Conversational.Commerce.docx)
Attached is the text for a new page with title "Conversational Commerce Definition and Meaning". 
H1 should be "A Simple Look at the Key Components of Conversational Commerce". 
URL should be /glossary/conversational-commerce.
Banners and the block with B2B case studies should exist on the page.

**Comment by AndrewYunisov** [comment]
Please, also insert this picture - https://virto365.sharepoint.com/sites/VirtoCommerce/Shared%20Documents/Marketing/Demo/Bot/orderwise-flow2.gif
The text at the right from it should state: 
"Chat with your customers using automated bot.
Deliver the products instantly with personal, detailed messages about order options."
Button should be "Trial&Demo" like on our main page.
Example - https://screencast.com/t/Z7SlV9Xll

**Comment by tatarincev** [comment]
Done https://virtocommerce.com/glossary/conversational-commerce

**Comment by AndrewYunisov** [comment]
1. Some of the titles are done wrong. The bullets for Advanced Notifications Through Conversational Commerce, Bots Interfaces for Conversational Commerce and Chats in Apps
should not exist. Should be the same font as conclusion.
2.  Introduction -> Introduction into conversational commerce (should be H2, H2 should be met only once on the page, conclusion can be done just bold) 
3. Case study block should be after the first bulleted list.

**Comment by blazemachine** [comment]
Now it will be looking like that:
![vccom-glossary-conversational-commerce](https://user-images.githubusercontent.com/43133766/49437952-b669fd80-f7de-11e8-9af0-c4be8e71e1e0.png)

**Comment by AndrewYunisov** [comment]
Ideal. Please, release it.

**Comment by AndrewYunisov** [comment]
I am foolish, forgot to say what should be when the button "Trial & Demo" is clicked. Please, do the same what happens with our top right button.

**Comment by tatarincev** [comment]
Done  https://virtocommerce.com/glossary/conversational-commerce
